### ISSUE TITLE
Finish UI/UX in Figma

### ISSUE THREAD

**Issue by GuScarenci** [fossguild/joynride#39]
We need to finalize the screen designs in Figma to proceed with frontend development.

Below are some screens we already proposed and are still incomplete, but additional ones may need to be created to ensure a smooth app flow:

- [x] Screen for available trips based on search results
- [x] Screen to request a trip after viewing details
- [x] Screen to view trip details (for both the trip requester and provider)
- [x] Screen to confirm a recurring ride (for both the trip requester and provider)
- [x] Screen for messages
- [x] Screen for conversation
- [x] User profile screen

**Comment by cirillom** [comment]
This should be done with Figma dev mode features in mind, meaning that, we need to use components and it needs to be possible to navigate between different screens using the buttons

**Comment by bealomes** [comment]
Escolha de cores:
![image](https://github.com/user-attachments/assets/9bcb5829-bbfe-4c26-9ea2-c4598f82a04f)

**Comment by GuScarenci** [comment]
![image](https://github.com/user-attachments/assets/70084318-f619-4dfa-92f9-17da918fcac2)

**Comment by cirillom** [comment]
Dialogs that need to be implemented:
- [ ] Oferecer: shows path with arrival prediction and asks user to confirm if he really wants to offer
- [ ] Caronas: filter by: date, departure, destination
- [ ] Busca de caronas: filter by: hour, driver rating, driver male/female, max distance from departure, max distance from destination 
- [ ] Mensagens: filter by read/unread, drivers where you have a scheduled ride

**Comment by cirillom** [comment]
First round of screens done, still missing:
- [ ] App flow with Prototype
- [ ] Dialogs


![image](https://github.com/user-attachments/assets/e56e7186-e0b9-4df7-bda6-279a80e99458)
